services:
  # Frontend Static Site - Standalone
  - type: static
    name: apex-frontend
    buildCommand: |
      cd frontend
      npm ci
      npm run export
    staticPublishPath: frontend/out
    envVars:
      - key: NODE_VERSION
        value: 20.11.0 