services:
  # API Backend Service
  - type: web
    name: apex-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    numInstances: 1
    
  # Frontend Static Site
  - type: web  
    name: apex-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run export
    staticPublishPath: frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: apex-api
          type: web
          property: url
      - key: NODE_VERSION
        value: 18.17.0 